Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2022
Var
// Seção de Declarações das variáveis 
a:real
resultado:real

inicio
// Seção de Comandos
escreval("Digite um número, este algoritimo mostrará o numero anterior a ele: ")
leia(a)
resultado <- a-1
escreval(resultado)

fimalgoritmo

