algoritmo "trocar valores"
// Função : Armazena 10 em A e 20 em B,
//troca os valores de A por B e mostra
//na tela final
// Autor : Bianca Prado
// Data : 07/03/2022
// Seção de Declarações 
var
a,b,c:inteiro

inicio
// Seção de Comandos
a <-10
b <-20
c <-a
a <-b
b <-c
escreval("***********************")
escreval("* o valor de a é: ",a," *")
escreval("*                     *")
escreval("* o valor de b é: ",b," *")
escreval("***********************")

fimalgoritmo
