Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2022
Var
// Seção de Declarações das variáveis 
a,b,c:real


inicio
// Seção de Comandos
escreval("digite o valor de a: ")
leia(a)
escreval("digite o valor de b: ")
leia(b)
c <- a
a <- b
b <- c

escreval("o valor de a é: ",a,"")
escreval("o valor de b é: ",b,"")






fimalgoritmo

