algoritmo "semnome"
// Função :
// Autor :
// Data : 25/04/2022
// Seção de Declarações 
var
qtde_minima:real
qtde_maxima:real
estoque_medio:real
inicio

// Dados de Entrada
escreval("Digite o valor de quantidade minima: ")
leia(qtde_minima)
escreval("Digite o valor de quantidade maxima: ")
leia(qtde_maxima)

//Processamento
estoque_medio <- (qtde_minima+qtde_maxima)/2

//Saída
escreval("O estoque médio é: ",estoque_medio)

fimalgoritmo
