algoritmo "semnome"
// Função :
// Autor :
// Data : 02/05/2022
// Seção de Declarações 
var
cotacao:real
valor_reais:real
valor_dolar:real
inicio
//Dados de Entrada
escreval("Digite o valor de cotação: ")
leia(cotacao)
escreval("DIgite a quantia em reais: ")
leia(valor_reais)

//Processamentos
valor_dolar <-valor_reais/cotacao

//Dados de Saída
escreval("o valor em dólar é: ",valor_dolar)   '

fimalgoritmo
