algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2022
// Seção de Declarações 
var
preco_custo:real
imposto:real
transporte:real
custo_final:real
inicio
// Dados de Entrada
escreval("Digite o valor do carro: ",preco_custo)
leia(preco_custo)

imposto <- preco_custo*1.45

transporte <- imposto*1.28

custo_final <- transporte

//Dados de Saída
escreval("O valor dinal do consumidor é: ",custo_final)
fimalgoritmo
